// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Order.proto

package com.wjy.learn.protobuf.dto;

public final class OrderProto {
  private OrderProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * 枚举类型
   * </pre>
   *
   * Protobuf enum {@code OrderType}
   */
  public enum OrderType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>TRADE = 0;</code>
     */
    TRADE(0),
    /**
     * <code>REFUND = 1;</code>
     */
    REFUND(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>TRADE = 0;</code>
     */
    public static final int TRADE_VALUE = 0;
    /**
     * <code>REFUND = 1;</code>
     */
    public static final int REFUND_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static OrderType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static OrderType forNumber(int value) {
      switch (value) {
        case 0: return TRADE;
        case 1: return REFUND;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<OrderType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        OrderType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<OrderType>() {
            public OrderType findValueByNumber(int number) {
              return OrderType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.wjy.learn.protobuf.dto.OrderProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final OrderType[] VALUES = values();

    public static OrderType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private OrderType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:OrderType)
  }

  public interface OrderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Order)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>.OrderType orderType = 2;</code>
     * @return The enum numeric value on the wire for orderType.
     */
    int getOrderTypeValue();
    /**
     * <code>.OrderType orderType = 2;</code>
     * @return The orderType.
     */
    com.wjy.learn.protobuf.dto.OrderProto.OrderType getOrderType();

    /**
     * <code>string orderName = 3;</code>
     * @return The orderName.
     */
    java.lang.String getOrderName();
    /**
     * <code>string orderName = 3;</code>
     * @return The bytes for orderName.
     */
    com.google.protobuf.ByteString
        getOrderNameBytes();

    /**
     * <code>int64 userId = 4;</code>
     * @return The userId.
     */
    long getUserId();

    /**
     * <pre>
     * 重复list
     * </pre>
     *
     * <code>repeated string remark = 5;</code>
     * @return A list containing the remark.
     */
    java.util.List<java.lang.String>
        getRemarkList();
    /**
     * <pre>
     * 重复list
     * </pre>
     *
     * <code>repeated string remark = 5;</code>
     * @return The count of remark.
     */
    int getRemarkCount();
    /**
     * <pre>
     * 重复list
     * </pre>
     *
     * <code>repeated string remark = 5;</code>
     * @param index The index of the element to return.
     * @return The remark at the given index.
     */
    java.lang.String getRemark(int index);
    /**
     * <pre>
     * 重复list
     * </pre>
     *
     * <code>repeated string remark = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the remark at the given index.
     */
    com.google.protobuf.ByteString
        getRemarkBytes(int index);

    /**
     * <pre>
     * 嵌套对象的map
     * </pre>
     *
     * <code>map&lt;int32, .GoodDetail&gt; goods = 6;</code>
     */
    int getGoodsCount();
    /**
     * <pre>
     * 嵌套对象的map
     * </pre>
     *
     * <code>map&lt;int32, .GoodDetail&gt; goods = 6;</code>
     */
    boolean containsGoods(
        int key);
    /**
     * Use {@link #getGoodsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, com.wjy.learn.protobuf.dto.OrderProto.GoodDetail>
    getGoods();
    /**
     * <pre>
     * 嵌套对象的map
     * </pre>
     *
     * <code>map&lt;int32, .GoodDetail&gt; goods = 6;</code>
     */
    java.util.Map<java.lang.Integer, com.wjy.learn.protobuf.dto.OrderProto.GoodDetail>
    getGoodsMap();
    /**
     * <pre>
     * 嵌套对象的map
     * </pre>
     *
     * <code>map&lt;int32, .GoodDetail&gt; goods = 6;</code>
     */

    com.wjy.learn.protobuf.dto.OrderProto.GoodDetail getGoodsOrDefault(
        int key,
        com.wjy.learn.protobuf.dto.OrderProto.GoodDetail defaultValue);
    /**
     * <pre>
     * 嵌套对象的map
     * </pre>
     *
     * <code>map&lt;int32, .GoodDetail&gt; goods = 6;</code>
     */

    com.wjy.learn.protobuf.dto.OrderProto.GoodDetail getGoodsOrThrow(
        int key);
  }
  /**
   * <pre>
   * 使用message关键字定义成员，每个变量都有唯一的数字标志。一个文件里可定义多个message
   * </pre>
   *
   * Protobuf type {@code Order}
   */
  public static final class Order extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Order)
      OrderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Order.newBuilder() to construct.
    private Order(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Order() {
      orderType_ = 0;
      orderName_ = "";
      remark_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Order();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Order(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              orderType_ = rawValue;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              orderName_ = s;
              break;
            }
            case 32: {

              userId_ = input.readInt64();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                remark_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              remark_.add(s);
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                goods_ = com.google.protobuf.MapField.newMapField(
                    GoodsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, com.wjy.learn.protobuf.dto.OrderProto.GoodDetail>
              goods__ = input.readMessage(
                  GoodsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              goods_.getMutableMap().put(
                  goods__.getKey(), goods__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          remark_ = remark_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wjy.learn.protobuf.dto.OrderProto.internal_static_Order_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetGoods();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wjy.learn.protobuf.dto.OrderProto.internal_static_Order_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wjy.learn.protobuf.dto.OrderProto.Order.class, com.wjy.learn.protobuf.dto.OrderProto.Order.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int ORDERTYPE_FIELD_NUMBER = 2;
    private int orderType_;
    /**
     * <code>.OrderType orderType = 2;</code>
     * @return The enum numeric value on the wire for orderType.
     */
    @java.lang.Override public int getOrderTypeValue() {
      return orderType_;
    }
    /**
     * <code>.OrderType orderType = 2;</code>
     * @return The orderType.
     */
    @java.lang.Override public com.wjy.learn.protobuf.dto.OrderProto.OrderType getOrderType() {
      @SuppressWarnings("deprecation")
      com.wjy.learn.protobuf.dto.OrderProto.OrderType result = com.wjy.learn.protobuf.dto.OrderProto.OrderType.valueOf(orderType_);
      return result == null ? com.wjy.learn.protobuf.dto.OrderProto.OrderType.UNRECOGNIZED : result;
    }

    public static final int ORDERNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object orderName_;
    /**
     * <code>string orderName = 3;</code>
     * @return The orderName.
     */
    @java.lang.Override
    public java.lang.String getOrderName() {
      java.lang.Object ref = orderName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orderName_ = s;
        return s;
      }
    }
    /**
     * <code>string orderName = 3;</code>
     * @return The bytes for orderName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOrderNameBytes() {
      java.lang.Object ref = orderName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orderName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERID_FIELD_NUMBER = 4;
    private long userId_;
    /**
     * <code>int64 userId = 4;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }

    public static final int REMARK_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList remark_;
    /**
     * <pre>
     * 重复list
     * </pre>
     *
     * <code>repeated string remark = 5;</code>
     * @return A list containing the remark.
     */
    public com.google.protobuf.ProtocolStringList
        getRemarkList() {
      return remark_;
    }
    /**
     * <pre>
     * 重复list
     * </pre>
     *
     * <code>repeated string remark = 5;</code>
     * @return The count of remark.
     */
    public int getRemarkCount() {
      return remark_.size();
    }
    /**
     * <pre>
     * 重复list
     * </pre>
     *
     * <code>repeated string remark = 5;</code>
     * @param index The index of the element to return.
     * @return The remark at the given index.
     */
    public java.lang.String getRemark(int index) {
      return remark_.get(index);
    }
    /**
     * <pre>
     * 重复list
     * </pre>
     *
     * <code>repeated string remark = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the remark at the given index.
     */
    public com.google.protobuf.ByteString
        getRemarkBytes(int index) {
      return remark_.getByteString(index);
    }

    public static final int GOODS_FIELD_NUMBER = 6;
    private static final class GoodsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, com.wjy.learn.protobuf.dto.OrderProto.GoodDetail> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, com.wjy.learn.protobuf.dto.OrderProto.GoodDetail>newDefaultInstance(
                  com.wjy.learn.protobuf.dto.OrderProto.internal_static_Order_GoodsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.wjy.learn.protobuf.dto.OrderProto.GoodDetail.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, com.wjy.learn.protobuf.dto.OrderProto.GoodDetail> goods_;
    private com.google.protobuf.MapField<java.lang.Integer, com.wjy.learn.protobuf.dto.OrderProto.GoodDetail>
    internalGetGoods() {
      if (goods_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            GoodsDefaultEntryHolder.defaultEntry);
      }
      return goods_;
    }

    public int getGoodsCount() {
      return internalGetGoods().getMap().size();
    }
    /**
     * <pre>
     * 嵌套对象的map
     * </pre>
     *
     * <code>map&lt;int32, .GoodDetail&gt; goods = 6;</code>
     */

    @java.lang.Override
    public boolean containsGoods(
        int key) {
      
      return internalGetGoods().getMap().containsKey(key);
    }
    /**
     * Use {@link #getGoodsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, com.wjy.learn.protobuf.dto.OrderProto.GoodDetail> getGoods() {
      return getGoodsMap();
    }
    /**
     * <pre>
     * 嵌套对象的map
     * </pre>
     *
     * <code>map&lt;int32, .GoodDetail&gt; goods = 6;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.Integer, com.wjy.learn.protobuf.dto.OrderProto.GoodDetail> getGoodsMap() {
      return internalGetGoods().getMap();
    }
    /**
     * <pre>
     * 嵌套对象的map
     * </pre>
     *
     * <code>map&lt;int32, .GoodDetail&gt; goods = 6;</code>
     */
    @java.lang.Override

    public com.wjy.learn.protobuf.dto.OrderProto.GoodDetail getGoodsOrDefault(
        int key,
        com.wjy.learn.protobuf.dto.OrderProto.GoodDetail defaultValue) {
      
      java.util.Map<java.lang.Integer, com.wjy.learn.protobuf.dto.OrderProto.GoodDetail> map =
          internalGetGoods().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * 嵌套对象的map
     * </pre>
     *
     * <code>map&lt;int32, .GoodDetail&gt; goods = 6;</code>
     */
    @java.lang.Override

    public com.wjy.learn.protobuf.dto.OrderProto.GoodDetail getGoodsOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, com.wjy.learn.protobuf.dto.OrderProto.GoodDetail> map =
          internalGetGoods().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (orderType_ != com.wjy.learn.protobuf.dto.OrderProto.OrderType.TRADE.getNumber()) {
        output.writeEnum(2, orderType_);
      }
      if (!getOrderNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, orderName_);
      }
      if (userId_ != 0L) {
        output.writeInt64(4, userId_);
      }
      for (int i = 0; i < remark_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, remark_.getRaw(i));
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeIntegerMapTo(
          output,
          internalGetGoods(),
          GoodsDefaultEntryHolder.defaultEntry,
          6);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (orderType_ != com.wjy.learn.protobuf.dto.OrderProto.OrderType.TRADE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, orderType_);
      }
      if (!getOrderNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, orderName_);
      }
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, userId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < remark_.size(); i++) {
          dataSize += computeStringSizeNoTag(remark_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getRemarkList().size();
      }
      for (java.util.Map.Entry<java.lang.Integer, com.wjy.learn.protobuf.dto.OrderProto.GoodDetail> entry
           : internalGetGoods().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, com.wjy.learn.protobuf.dto.OrderProto.GoodDetail>
        goods__ = GoodsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(6, goods__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wjy.learn.protobuf.dto.OrderProto.Order)) {
        return super.equals(obj);
      }
      com.wjy.learn.protobuf.dto.OrderProto.Order other = (com.wjy.learn.protobuf.dto.OrderProto.Order) obj;

      if (getId()
          != other.getId()) return false;
      if (orderType_ != other.orderType_) return false;
      if (!getOrderName()
          .equals(other.getOrderName())) return false;
      if (getUserId()
          != other.getUserId()) return false;
      if (!getRemarkList()
          .equals(other.getRemarkList())) return false;
      if (!internalGetGoods().equals(
          other.internalGetGoods())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + ORDERTYPE_FIELD_NUMBER;
      hash = (53 * hash) + orderType_;
      hash = (37 * hash) + ORDERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getOrderName().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      if (getRemarkCount() > 0) {
        hash = (37 * hash) + REMARK_FIELD_NUMBER;
        hash = (53 * hash) + getRemarkList().hashCode();
      }
      if (!internalGetGoods().getMap().isEmpty()) {
        hash = (37 * hash) + GOODS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetGoods().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wjy.learn.protobuf.dto.OrderProto.Order parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjy.learn.protobuf.dto.OrderProto.Order parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjy.learn.protobuf.dto.OrderProto.Order parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjy.learn.protobuf.dto.OrderProto.Order parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjy.learn.protobuf.dto.OrderProto.Order parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjy.learn.protobuf.dto.OrderProto.Order parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjy.learn.protobuf.dto.OrderProto.Order parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wjy.learn.protobuf.dto.OrderProto.Order parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wjy.learn.protobuf.dto.OrderProto.Order parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wjy.learn.protobuf.dto.OrderProto.Order parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wjy.learn.protobuf.dto.OrderProto.Order parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wjy.learn.protobuf.dto.OrderProto.Order parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wjy.learn.protobuf.dto.OrderProto.Order prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 使用message关键字定义成员，每个变量都有唯一的数字标志。一个文件里可定义多个message
     * </pre>
     *
     * Protobuf type {@code Order}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Order)
        com.wjy.learn.protobuf.dto.OrderProto.OrderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wjy.learn.protobuf.dto.OrderProto.internal_static_Order_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetGoods();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetMutableGoods();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wjy.learn.protobuf.dto.OrderProto.internal_static_Order_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wjy.learn.protobuf.dto.OrderProto.Order.class, com.wjy.learn.protobuf.dto.OrderProto.Order.Builder.class);
      }

      // Construct using com.wjy.learn.protobuf.dto.OrderProto.Order.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        orderType_ = 0;

        orderName_ = "";

        userId_ = 0L;

        remark_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        internalGetMutableGoods().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wjy.learn.protobuf.dto.OrderProto.internal_static_Order_descriptor;
      }

      @java.lang.Override
      public com.wjy.learn.protobuf.dto.OrderProto.Order getDefaultInstanceForType() {
        return com.wjy.learn.protobuf.dto.OrderProto.Order.getDefaultInstance();
      }

      @java.lang.Override
      public com.wjy.learn.protobuf.dto.OrderProto.Order build() {
        com.wjy.learn.protobuf.dto.OrderProto.Order result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.wjy.learn.protobuf.dto.OrderProto.Order buildPartial() {
        com.wjy.learn.protobuf.dto.OrderProto.Order result = new com.wjy.learn.protobuf.dto.OrderProto.Order(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.orderType_ = orderType_;
        result.orderName_ = orderName_;
        result.userId_ = userId_;
        if (((bitField0_ & 0x00000001) != 0)) {
          remark_ = remark_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.remark_ = remark_;
        result.goods_ = internalGetGoods();
        result.goods_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wjy.learn.protobuf.dto.OrderProto.Order) {
          return mergeFrom((com.wjy.learn.protobuf.dto.OrderProto.Order)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wjy.learn.protobuf.dto.OrderProto.Order other) {
        if (other == com.wjy.learn.protobuf.dto.OrderProto.Order.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.orderType_ != 0) {
          setOrderTypeValue(other.getOrderTypeValue());
        }
        if (!other.getOrderName().isEmpty()) {
          orderName_ = other.orderName_;
          onChanged();
        }
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (!other.remark_.isEmpty()) {
          if (remark_.isEmpty()) {
            remark_ = other.remark_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRemarkIsMutable();
            remark_.addAll(other.remark_);
          }
          onChanged();
        }
        internalGetMutableGoods().mergeFrom(
            other.internalGetGoods());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wjy.learn.protobuf.dto.OrderProto.Order parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wjy.learn.protobuf.dto.OrderProto.Order) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private int orderType_ = 0;
      /**
       * <code>.OrderType orderType = 2;</code>
       * @return The enum numeric value on the wire for orderType.
       */
      @java.lang.Override public int getOrderTypeValue() {
        return orderType_;
      }
      /**
       * <code>.OrderType orderType = 2;</code>
       * @param value The enum numeric value on the wire for orderType to set.
       * @return This builder for chaining.
       */
      public Builder setOrderTypeValue(int value) {
        
        orderType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.OrderType orderType = 2;</code>
       * @return The orderType.
       */
      @java.lang.Override
      public com.wjy.learn.protobuf.dto.OrderProto.OrderType getOrderType() {
        @SuppressWarnings("deprecation")
        com.wjy.learn.protobuf.dto.OrderProto.OrderType result = com.wjy.learn.protobuf.dto.OrderProto.OrderType.valueOf(orderType_);
        return result == null ? com.wjy.learn.protobuf.dto.OrderProto.OrderType.UNRECOGNIZED : result;
      }
      /**
       * <code>.OrderType orderType = 2;</code>
       * @param value The orderType to set.
       * @return This builder for chaining.
       */
      public Builder setOrderType(com.wjy.learn.protobuf.dto.OrderProto.OrderType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        orderType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.OrderType orderType = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOrderType() {
        
        orderType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object orderName_ = "";
      /**
       * <code>string orderName = 3;</code>
       * @return The orderName.
       */
      public java.lang.String getOrderName() {
        java.lang.Object ref = orderName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          orderName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string orderName = 3;</code>
       * @return The bytes for orderName.
       */
      public com.google.protobuf.ByteString
          getOrderNameBytes() {
        java.lang.Object ref = orderName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          orderName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string orderName = 3;</code>
       * @param value The orderName to set.
       * @return This builder for chaining.
       */
      public Builder setOrderName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        orderName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string orderName = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearOrderName() {
        
        orderName_ = getDefaultInstance().getOrderName();
        onChanged();
        return this;
      }
      /**
       * <code>string orderName = 3;</code>
       * @param value The bytes for orderName to set.
       * @return This builder for chaining.
       */
      public Builder setOrderNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        orderName_ = value;
        onChanged();
        return this;
      }

      private long userId_ ;
      /**
       * <code>int64 userId = 4;</code>
       * @return The userId.
       */
      @java.lang.Override
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>int64 userId = 4;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(long value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 userId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        
        userId_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList remark_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureRemarkIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          remark_ = new com.google.protobuf.LazyStringArrayList(remark_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * 重复list
       * </pre>
       *
       * <code>repeated string remark = 5;</code>
       * @return A list containing the remark.
       */
      public com.google.protobuf.ProtocolStringList
          getRemarkList() {
        return remark_.getUnmodifiableView();
      }
      /**
       * <pre>
       * 重复list
       * </pre>
       *
       * <code>repeated string remark = 5;</code>
       * @return The count of remark.
       */
      public int getRemarkCount() {
        return remark_.size();
      }
      /**
       * <pre>
       * 重复list
       * </pre>
       *
       * <code>repeated string remark = 5;</code>
       * @param index The index of the element to return.
       * @return The remark at the given index.
       */
      public java.lang.String getRemark(int index) {
        return remark_.get(index);
      }
      /**
       * <pre>
       * 重复list
       * </pre>
       *
       * <code>repeated string remark = 5;</code>
       * @param index The index of the value to return.
       * @return The bytes of the remark at the given index.
       */
      public com.google.protobuf.ByteString
          getRemarkBytes(int index) {
        return remark_.getByteString(index);
      }
      /**
       * <pre>
       * 重复list
       * </pre>
       *
       * <code>repeated string remark = 5;</code>
       * @param index The index to set the value at.
       * @param value The remark to set.
       * @return This builder for chaining.
       */
      public Builder setRemark(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRemarkIsMutable();
        remark_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 重复list
       * </pre>
       *
       * <code>repeated string remark = 5;</code>
       * @param value The remark to add.
       * @return This builder for chaining.
       */
      public Builder addRemark(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRemarkIsMutable();
        remark_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 重复list
       * </pre>
       *
       * <code>repeated string remark = 5;</code>
       * @param values The remark to add.
       * @return This builder for chaining.
       */
      public Builder addAllRemark(
          java.lang.Iterable<java.lang.String> values) {
        ensureRemarkIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, remark_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 重复list
       * </pre>
       *
       * <code>repeated string remark = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearRemark() {
        remark_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 重复list
       * </pre>
       *
       * <code>repeated string remark = 5;</code>
       * @param value The bytes of the remark to add.
       * @return This builder for chaining.
       */
      public Builder addRemarkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureRemarkIsMutable();
        remark_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.Integer, com.wjy.learn.protobuf.dto.OrderProto.GoodDetail> goods_;
      private com.google.protobuf.MapField<java.lang.Integer, com.wjy.learn.protobuf.dto.OrderProto.GoodDetail>
      internalGetGoods() {
        if (goods_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              GoodsDefaultEntryHolder.defaultEntry);
        }
        return goods_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, com.wjy.learn.protobuf.dto.OrderProto.GoodDetail>
      internalGetMutableGoods() {
        onChanged();;
        if (goods_ == null) {
          goods_ = com.google.protobuf.MapField.newMapField(
              GoodsDefaultEntryHolder.defaultEntry);
        }
        if (!goods_.isMutable()) {
          goods_ = goods_.copy();
        }
        return goods_;
      }

      public int getGoodsCount() {
        return internalGetGoods().getMap().size();
      }
      /**
       * <pre>
       * 嵌套对象的map
       * </pre>
       *
       * <code>map&lt;int32, .GoodDetail&gt; goods = 6;</code>
       */

      @java.lang.Override
      public boolean containsGoods(
          int key) {
        
        return internalGetGoods().getMap().containsKey(key);
      }
      /**
       * Use {@link #getGoodsMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, com.wjy.learn.protobuf.dto.OrderProto.GoodDetail> getGoods() {
        return getGoodsMap();
      }
      /**
       * <pre>
       * 嵌套对象的map
       * </pre>
       *
       * <code>map&lt;int32, .GoodDetail&gt; goods = 6;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.Integer, com.wjy.learn.protobuf.dto.OrderProto.GoodDetail> getGoodsMap() {
        return internalGetGoods().getMap();
      }
      /**
       * <pre>
       * 嵌套对象的map
       * </pre>
       *
       * <code>map&lt;int32, .GoodDetail&gt; goods = 6;</code>
       */
      @java.lang.Override

      public com.wjy.learn.protobuf.dto.OrderProto.GoodDetail getGoodsOrDefault(
          int key,
          com.wjy.learn.protobuf.dto.OrderProto.GoodDetail defaultValue) {
        
        java.util.Map<java.lang.Integer, com.wjy.learn.protobuf.dto.OrderProto.GoodDetail> map =
            internalGetGoods().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * 嵌套对象的map
       * </pre>
       *
       * <code>map&lt;int32, .GoodDetail&gt; goods = 6;</code>
       */
      @java.lang.Override

      public com.wjy.learn.protobuf.dto.OrderProto.GoodDetail getGoodsOrThrow(
          int key) {
        
        java.util.Map<java.lang.Integer, com.wjy.learn.protobuf.dto.OrderProto.GoodDetail> map =
            internalGetGoods().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearGoods() {
        internalGetMutableGoods().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       * 嵌套对象的map
       * </pre>
       *
       * <code>map&lt;int32, .GoodDetail&gt; goods = 6;</code>
       */

      public Builder removeGoods(
          int key) {
        
        internalGetMutableGoods().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, com.wjy.learn.protobuf.dto.OrderProto.GoodDetail>
      getMutableGoods() {
        return internalGetMutableGoods().getMutableMap();
      }
      /**
       * <pre>
       * 嵌套对象的map
       * </pre>
       *
       * <code>map&lt;int32, .GoodDetail&gt; goods = 6;</code>
       */
      public Builder putGoods(
          int key,
          com.wjy.learn.protobuf.dto.OrderProto.GoodDetail value) {
        
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableGoods().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       * 嵌套对象的map
       * </pre>
       *
       * <code>map&lt;int32, .GoodDetail&gt; goods = 6;</code>
       */

      public Builder putAllGoods(
          java.util.Map<java.lang.Integer, com.wjy.learn.protobuf.dto.OrderProto.GoodDetail> values) {
        internalGetMutableGoods().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Order)
    }

    // @@protoc_insertion_point(class_scope:Order)
    private static final com.wjy.learn.protobuf.dto.OrderProto.Order DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wjy.learn.protobuf.dto.OrderProto.Order();
    }

    public static com.wjy.learn.protobuf.dto.OrderProto.Order getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Order>
        PARSER = new com.google.protobuf.AbstractParser<Order>() {
      @java.lang.Override
      public Order parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Order(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Order> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Order> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.wjy.learn.protobuf.dto.OrderProto.Order getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GoodDetailOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GoodDetail)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string goodName = 1;</code>
     * @return The goodName.
     */
    java.lang.String getGoodName();
    /**
     * <code>string goodName = 1;</code>
     * @return The bytes for goodName.
     */
    com.google.protobuf.ByteString
        getGoodNameBytes();
  }
  /**
   * Protobuf type {@code GoodDetail}
   */
  public static final class GoodDetail extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:GoodDetail)
      GoodDetailOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GoodDetail.newBuilder() to construct.
    private GoodDetail(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GoodDetail() {
      goodName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GoodDetail();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GoodDetail(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              goodName_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wjy.learn.protobuf.dto.OrderProto.internal_static_GoodDetail_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wjy.learn.protobuf.dto.OrderProto.internal_static_GoodDetail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wjy.learn.protobuf.dto.OrderProto.GoodDetail.class, com.wjy.learn.protobuf.dto.OrderProto.GoodDetail.Builder.class);
    }

    public static final int GOODNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object goodName_;
    /**
     * <code>string goodName = 1;</code>
     * @return The goodName.
     */
    @java.lang.Override
    public java.lang.String getGoodName() {
      java.lang.Object ref = goodName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        goodName_ = s;
        return s;
      }
    }
    /**
     * <code>string goodName = 1;</code>
     * @return The bytes for goodName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGoodNameBytes() {
      java.lang.Object ref = goodName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        goodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getGoodNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, goodName_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getGoodNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, goodName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wjy.learn.protobuf.dto.OrderProto.GoodDetail)) {
        return super.equals(obj);
      }
      com.wjy.learn.protobuf.dto.OrderProto.GoodDetail other = (com.wjy.learn.protobuf.dto.OrderProto.GoodDetail) obj;

      if (!getGoodName()
          .equals(other.getGoodName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GOODNAME_FIELD_NUMBER;
      hash = (53 * hash) + getGoodName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wjy.learn.protobuf.dto.OrderProto.GoodDetail parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjy.learn.protobuf.dto.OrderProto.GoodDetail parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjy.learn.protobuf.dto.OrderProto.GoodDetail parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjy.learn.protobuf.dto.OrderProto.GoodDetail parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjy.learn.protobuf.dto.OrderProto.GoodDetail parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wjy.learn.protobuf.dto.OrderProto.GoodDetail parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wjy.learn.protobuf.dto.OrderProto.GoodDetail parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wjy.learn.protobuf.dto.OrderProto.GoodDetail parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wjy.learn.protobuf.dto.OrderProto.GoodDetail parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wjy.learn.protobuf.dto.OrderProto.GoodDetail parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wjy.learn.protobuf.dto.OrderProto.GoodDetail parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wjy.learn.protobuf.dto.OrderProto.GoodDetail parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wjy.learn.protobuf.dto.OrderProto.GoodDetail prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GoodDetail}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GoodDetail)
        com.wjy.learn.protobuf.dto.OrderProto.GoodDetailOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wjy.learn.protobuf.dto.OrderProto.internal_static_GoodDetail_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wjy.learn.protobuf.dto.OrderProto.internal_static_GoodDetail_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wjy.learn.protobuf.dto.OrderProto.GoodDetail.class, com.wjy.learn.protobuf.dto.OrderProto.GoodDetail.Builder.class);
      }

      // Construct using com.wjy.learn.protobuf.dto.OrderProto.GoodDetail.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        goodName_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wjy.learn.protobuf.dto.OrderProto.internal_static_GoodDetail_descriptor;
      }

      @java.lang.Override
      public com.wjy.learn.protobuf.dto.OrderProto.GoodDetail getDefaultInstanceForType() {
        return com.wjy.learn.protobuf.dto.OrderProto.GoodDetail.getDefaultInstance();
      }

      @java.lang.Override
      public com.wjy.learn.protobuf.dto.OrderProto.GoodDetail build() {
        com.wjy.learn.protobuf.dto.OrderProto.GoodDetail result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.wjy.learn.protobuf.dto.OrderProto.GoodDetail buildPartial() {
        com.wjy.learn.protobuf.dto.OrderProto.GoodDetail result = new com.wjy.learn.protobuf.dto.OrderProto.GoodDetail(this);
        result.goodName_ = goodName_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wjy.learn.protobuf.dto.OrderProto.GoodDetail) {
          return mergeFrom((com.wjy.learn.protobuf.dto.OrderProto.GoodDetail)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wjy.learn.protobuf.dto.OrderProto.GoodDetail other) {
        if (other == com.wjy.learn.protobuf.dto.OrderProto.GoodDetail.getDefaultInstance()) return this;
        if (!other.getGoodName().isEmpty()) {
          goodName_ = other.goodName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wjy.learn.protobuf.dto.OrderProto.GoodDetail parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wjy.learn.protobuf.dto.OrderProto.GoodDetail) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object goodName_ = "";
      /**
       * <code>string goodName = 1;</code>
       * @return The goodName.
       */
      public java.lang.String getGoodName() {
        java.lang.Object ref = goodName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          goodName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string goodName = 1;</code>
       * @return The bytes for goodName.
       */
      public com.google.protobuf.ByteString
          getGoodNameBytes() {
        java.lang.Object ref = goodName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          goodName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string goodName = 1;</code>
       * @param value The goodName to set.
       * @return This builder for chaining.
       */
      public Builder setGoodName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        goodName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string goodName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearGoodName() {
        
        goodName_ = getDefaultInstance().getGoodName();
        onChanged();
        return this;
      }
      /**
       * <code>string goodName = 1;</code>
       * @param value The bytes for goodName to set.
       * @return This builder for chaining.
       */
      public Builder setGoodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        goodName_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:GoodDetail)
    }

    // @@protoc_insertion_point(class_scope:GoodDetail)
    private static final com.wjy.learn.protobuf.dto.OrderProto.GoodDetail DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wjy.learn.protobuf.dto.OrderProto.GoodDetail();
    }

    public static com.wjy.learn.protobuf.dto.OrderProto.GoodDetail getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GoodDetail>
        PARSER = new com.google.protobuf.AbstractParser<GoodDetail>() {
      @java.lang.Override
      public GoodDetail parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GoodDetail(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GoodDetail> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GoodDetail> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.wjy.learn.protobuf.dto.OrderProto.GoodDetail getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Order_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Order_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Order_GoodsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Order_GoodsEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GoodDetail_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GoodDetail_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Order.proto\"\302\001\n\005Order\022\n\n\002id\030\001 \001(\003\022\035\n\to" +
      "rderType\030\002 \001(\0162\n.OrderType\022\021\n\torderName\030" +
      "\003 \001(\t\022\016\n\006userId\030\004 \001(\003\022\016\n\006remark\030\005 \003(\t\022 \n" +
      "\005goods\030\006 \003(\0132\021.Order.GoodsEntry\0329\n\nGoods" +
      "Entry\022\013\n\003key\030\001 \001(\005\022\032\n\005value\030\002 \001(\0132\013.Good" +
      "Detail:\0028\001\"\036\n\nGoodDetail\022\020\n\010goodName\030\001 \001" +
      "(\t*\"\n\tOrderType\022\t\n\005TRADE\020\000\022\n\n\006REFUND\020\001B(" +
      "\n\032com.wjy.learn.protobuf.dtoB\nOrderProto" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Order_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Order_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Order_descriptor,
        new java.lang.String[] { "Id", "OrderType", "OrderName", "UserId", "Remark", "Goods", });
    internal_static_Order_GoodsEntry_descriptor =
      internal_static_Order_descriptor.getNestedTypes().get(0);
    internal_static_Order_GoodsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Order_GoodsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_GoodDetail_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GoodDetail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GoodDetail_descriptor,
        new java.lang.String[] { "GoodName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
